# gaming.yml (Job Template - Build Repo)
jobs:
- job: GamingJob
  pool:
    vmImage: 'ubuntu-latest'  # Microsoft-hosted agent
  steps:
    - script: echo "Hello, World!"
      displayName: "Run Hello World Script"
